DDCNL-2922 | Add PAYE multiple year functionality
hmrc/tax-summaries-frontend pull request #167
Opened 2020-10-21 11:09 UTC by jpatton638

2020-10-21 13:19 UTC, struong commented on test/controllers/paye/PayeAtsMainControllerSpec.scala
> +          val result = sut(true).show(fakeAuthenticatedRequest)
can we extract the true/false here or maybe two functions to create the two different types of services (one with multiple years shown and the other with one)?

2020-10-21 14:04 UTC, shikkhasingh requested changes

2020-10-21 14:34 UTC, jpatton638 commented on app/views/paye/PayeMultipleYearsView.scala.html
> +}
No, if it is accessed then it will be the first page on the service a user will hit

2020-10-22 13:11 UTC, struong approved these changes

2020-11-09 13:10 UTC, shikkhasingh approved these changes

2020-11-11 14:14 UTC, shikkhasingh approved these changes

2020-11-11 14:15 UTC, shikkhasingh approved these changes

2020-11-11 14:27 UTC, struong commented on conf/app.routes
> -GET     /paye/main                                             controllers.paye.PayeAtsMainController.show
/paye/main is the link from the gov.uk page it will have to stay in for now

2020-11-12 09:15 UTC, struong approved these changes

2020-11-23 10:39 UTC, merged