Ddcnl 3134
hmrc/tax-summaries-frontend pull request #185
Opened 2020-11-24 18:09 UTC by Muhammad-Ali-Ahmad

2020-11-27 11:47 UTC, thirlz95 requested changes

2020-11-27 11:47 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +            """<span id="total-cg-tax-rate">"""+viewModel.totalCgTaxRate.percent+"""</span>"""))</p>
can you use plays StringInterpolation -> https://www.playframework.com/documentation/2.6.x/ScalaTemplates

2020-11-27 11:47 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +                    """<span id="entrepreneurs-relief-rate-before">"""+currencyAmountView(viewModel.entrepreneursReliefRateBefore)+"""</span>""",
as above check for using StringInterpolation from twirl

2020-11-27 11:47 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +                    """<span id="ordinary-rate-before">"""+currencyAmountView(viewModel.ordinaryRateBefore)+"""</span>""",
as above check for using StringInterpolation from twirl

2020-11-27 11:47 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +                    """<span id="upper-rate-before">"""+currencyAmountView(viewModel.upperRateBefore)+"""</span>""",
as above check for using StringInterpolation from twirl

2020-11-27 11:47 UTC, thirlz95 commented on app/views/IncomeBeforeTaxView.scala.html
> +          <tbody id="income-before-tax-table">
more of a question than something to action but couldn't this be rewritten almost using a map/case statments to pass the table rows statement and just pass variables to the first td message, id and which view model to save from having to rewrite each table row

2020-11-27 11:47 UTC, thirlz95 commented on app/views/NicsView.scala.html
> +          "<span id=\"total-cg-tax-rate\">"+positiveOrZero(viewModel.nicsAndTaxRate).percent+"</span>"))</p>
interpolation possibly here?

2020-11-27 12:01 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +                    """<span id="entrepreneurs-relief-rate-before">"""+currencyAmountView(viewModel.entrepreneursReliefRateBefore)+"""</span>""",
Resolving as ticket is just covering template upgrade

2020-11-27 12:02 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +                    """<span id="ordinary-rate-before">"""+currencyAmountView(viewModel.ordinaryRateBefore)+"""</span>""",
Resolving as ticket is just covering template upgrade

2020-11-27 12:02 UTC, thirlz95 commented on app/views/IncomeBeforeTaxView.scala.html
> +          <tbody id="income-before-tax-table">
Resolving as ticket is just covering template upgrade

2020-11-27 12:02 UTC, thirlz95 commented on app/views/CapitalGainsView.scala.html
> +                    """<span id="upper-rate-before">"""+currencyAmountView(viewModel.upperRateBefore)+"""</span>""",
Resolving as ticket is just covering template upgrade

2020-11-27 12:02 UTC, thirlz95 commented on app/views/NicsView.scala.html
> +          "<span id=\"total-cg-tax-rate\">"+positiveOrZero(viewModel.nicsAndTaxRate).percent+"</span>"))</p>
Resolving as ticket is just covering template upgrade

2020-11-27 12:06 UTC, thirlz95 approved these changes
From a template switch over i've not been able to spot any issues, earlier comments where mention upgrades in the templating but that isn't covered in this ticket.

2020-12-01 18:26 UTC, shikkhasingh approved these changes

2020-12-02 11:20 UTC, shikkhasingh approved these changes

2021-01-13 14:03 UTC, merged