DDCNL-6416: 2022 Gov Spend
hmrc/tax-summaries-frontend pull request #275
Opened 2022-10-03 12:57 UTC by Christian-QA

2022-10-10 10:25 UTC, BetaDraconis requested changes

2022-10-10 10:25 UTC, BetaDraconis commented on app/models/Year.scala
> +          println("3" * 100)
printlns left in code

2022-10-10 10:25 UTC, BetaDraconis commented on app/models/Year.scala
> +          println("4" * 100)
printlns left in code

2022-10-10 10:25 UTC, BetaDraconis commented on app/models/Year.scala
> +          JsError("Not a year") // TODO - Change
A TODO

2022-10-10 10:25 UTC, BetaDraconis commented on app/models/Year.scala
> +//  implicit def queryStringBindable: QueryStringBindable[Year] = new QueryStringBindable[Year] {
Is this supposed to still be here?

2022-10-10 12:14 UTC, BetaDraconis approved these changes

2022-10-11 14:13 UTC, pascal22p approved these changes

2022-10-27 13:16 UTC, pascal22p approved these changes

2022-10-28 13:24 UTC, pascal22p approved these changes

2022-10-31 12:43 UTC, merged